### ISSUE TITLE
Algebraic types

### ISSUE THREAD

**Issue by jeb2239** [Morgan-Stanley/hobbes#174]
Can I make a new algebraic type of variant? 
```
data foo_or_not = |foo:[char],hotdog:int|
println( 
    match (|foo="chicken"|::foo_or_not) with 
        | |foo=x| where x ==  "chicken" -> x 
        | |hotdog=_| -> "hi"
        | _ -> "hello"
)
```
It seems like this is not possible. As the compiler says that this is unsat when run hi -x -s file.hob

**Comment by kthielen** [comment]
Hey jeb!

You definitely can define your own types and type aliases.  If you change the keyword "data" in your example to "type", you should find that your program prints "chicken" as you expect (I tried it myself just now to be sure :)).

So what's the difference?  In hobbes, declarations introduced with "type" are interpreted as "type aliases" (basically copy/pasting definitions where used) whereas declarations introduced with "data" are interpreted as "opaque type definitions".

An opaque type definition has a "hidden representation type" (since the compiler has to know how to store the data, how large it is, etc) but is specifically intended to be distinct from its representation type.  And we want it to be distinct from its representation type since we want to interpret it in different ways (specialize it differently for type classes, usually).

For example, there's an internal data definition like:

data a@f = long

These things are meant to designate a "file pointer" (within the file 'f') to a value of type "a", but (like a memory pointer) they're represented by a long.  However, we wouldn't want them to print as a long (kind of useless) or even necessarily ordered like a long.

Does that make sense?

**Comment by jeb2239** [comment]
So I was wondering if it is possible to do something like 
http://learnyouahaskell.com/making-our-own-types-and-typeclasses
Bool is defined as a variant but it is also its own type. I could make another bool type defined the same way with just a different name but they would be recognized as being different types.

maybe foo_or_not needs a special constructor notation?

**Comment by kthielen** [comment]
So far we typically deal with types "structurally" (so prefer 'type N = ...' instead of 'data N = ...') and less often deal with types "nominally".  So far, in the few cases where I have introduced an opaque 'data' type, I have used 'unsafeCast' to map from its representation (and on the other hand can use unsafeCast or '.t' to map opaque types to their representation).

```
data MyBool = ()+()

troo = unsafeCast(just())::MyBool
fawls = unsafeCast(nothing::()+())::MyBool

instance Show MyBool where
  show x = either(x.t, "fawls", \_."troo")
```

And then:

```
$ hi -s mybool.hob
> :t troo
MyBool
> :t fawls
MyBool
> troo
troo
> fawls
fawls
```

**Comment by RomanShestakov** [comment]
this example gives me a different result:

$ hi -s ~/development/piramide/src/hobbes/myBool.hob
> :t troo
a
> :t fawls
a
> troo
/home/romanshestakov/development/piramide/src/hobbes/myBool.hob, /home/romanshestakov/development/piramide/src/hobbes/myBool.hob:2,1-33: troo is not allowed, its transitive closure has disabled expressions: {unsafeCast}.troo = unsafeCast(just(()))::MyBool


why this expression gets disabled in REPL and why expression gets disabled?
 or even more generally - what does "unsafe" expression mean? 
I also found a place in code when hi gets started with "Safe" option but couldn't find a way to start it with "unsafe mode"

Regards, Roman

**Comment by smunix** [comment]
IIRC, `hi -ono-Safe -s myBool.hob` is what you want
