### ISSUE TITLE
Hog recovers from stats log after restarting

### ISSUE THREAD

**Issue by chenkai036** [Morgan-Stanley/hobbes#225]
Upon a restart, hog should block new connections before it completes any outstanding file transmission previously.  The connection states can be retrieved from the stats log.

**Comment by hstalker** [comment]
I would like to clarify what exactly the desired behaviour is. Assuming the following scenario:
 
- A batchsend Hog instance stops or is killed etc. for some reason.
- A new Hog instance is spawned or started (possibly with different parameters).
- There are outstanding files to be transmitted to various previously connected batchrecv instances of Hog.

What do we want to do? An example of how I'm understanding it:

- The new Hog instance checks for outstanding files to be sent.
- Renegotiates connections by following (more detailed than what is there currently, for example destination, file sending progress) information from /var/tmp/hogstat.db (more specifically Senders recorded as not being closed at any point in the stats file).
- Completes transfer of said outstanding files.
- The new Hog instance then proceeds to perform whatever task it was given based on the parameter set.

Am I along the right lines here?

**Comment by hstalker** [comment]
In line with the above outlined approach, I present the following (writing this as a memo to self as much as publicising it):

- Augment the data structures logged to the stats file (/var/tmp/hogstat.db) to provide all crucial information for automatically recreating a batchsend session (recv hosts, ports, paths, status).
- Add the appropriate logging statements into the batchsend logic.
- Decouple normal batchsend flow from the core batchsend logic.
- Implement batchsend recovery mode using prior decoupled logic.
- Implement code for detecting prior faults via the stats file (for instance, already present segment files and senders that weren't logged as closed in stats).

One thing I'm unsure on is the best way of testing this. It seems like the most likely route will be via a similar method to the way execution engine restart and ordering is being tested for Hog (i.e. an in-test fork/exec method), though this'll likely be quite a bit more difficult due to the need to simulate incomplete transfer of segment data to some Hog recv.

**Comment by kthielen** [comment]
Great questions.

On the first set of questions, I think we want to ensure "safe, correct progress" as viewed from the final log.  So we need to send batches to the remote side in the right order, and part of this involves not sending new data until old data is fully sent.

If the hog process bounces and comes back (should be with the same config), then we also want to delay sending new data until old data has been sent.  However, hog can send to multiple destinations, which complicates this story somewhat.  Also, hog blocking recording of data can have an impact on processes that want to come up and start recording data.

As long as we can correctly order this data, we can unblock producer processes and queue up data in order.  As long as we can send to at least one remote process, we should send as much as we can (in the right order).

I hope that this clarifies the basic intent.
