### ISSUE TITLE
class info RTTI under clang

### ISSUE THREAD

**Issue by kthielen** [Morgan-Stanley/hobbes#24]
There's a useful feature in hobbes where it can infer your bound C++ class relationships so that if you want to write an expression that needs that information (e.g.: passing a derived class to a function that wants a base class) then you can do it.

For gcc/Linux, this uses the '__class_type_info' structures in __cxxabiv1 (which is where this feature was originally implemented).  For clang/OSX I couldn't find a way to get this same information, so I've disabled that functionality (and the corresponding unit tests) just on this platform.  If there's a way to get it back though, it would be very useful.

**Comment by jeb2239** [comment]
one thing could be we require you build with gcc on mac as well. or this
https://caesr.uwaterloo.ca/misc/boost-llvm-clang.html

**Comment by jeb2239** [comment]
A quote from above.

By default, LLVM and clang are compiled with the -fno-rtti flag. This means that RTTI support is disabled. However, when using libraries such as Boost, it is necessary to recompile LLVM and clang with RTTI enabled. While there is documentation on how to do it here, it happened to be more involved than just that.

We need to set the LLVM_REQUIRES_RTTI variable in order to get LLVM to compile with RTTI. Assuming $LLVM_ROOT is the directory location for the LLVM source, and $CLANG_ROOT points to the directory where clang is installed.

**Comment by kthielen** [comment]
I think it's not so much an issue of enabling RTTI -- that already has to be enabled because there's code in hobbes that uses 'dynamic_cast'.  But gcc provides this __cxxabiv1::__class_type_info set of types that describe relationships between program class types (e.g. that D derives from both M0 and M1 which both derive virtually from B, so hobbes can produce the code to cast from D to B).

I have seen conflicting info about whether it's possible to get this out of clang too, but at least in my system headers I don't see any way to get that info.

**Comment by skaller** [comment]
Exactly what information do you need? RTTI data is something it is best to not rely on since the whole system collapses with shared libraries due to a serious misdesign. C++17 allows you to ask if a class is derived from another, but I don't see why you need to know that if you're using a C++ compiler for binding, and I don't see any other way you can get it to work. you can generate all the LLVM you want but it will never map to C++ because you have to know the libraries to do that, and there's no standard for that (and clang and g++ aren't compatible). The C function ABI is standard though.

**Comment by kthielen** [comment]
We're just talking about the information in __class_type_info as above, which is provided by gcc.  The code in hobbes/lang/preds/subtype/obj.[C|H] is relevant here.

**Comment by skaller** [comment]
Not sure if this is relevant:

https://bibouh123.wordpress.com/2014/10/13/compile-llvm-with-enabling-rtti/

says you can patch clang to add g++ rtti abi support. Whether that's useful or not I don't know, i have no intention of changing my Xcode install.

**Comment by kthielen** [comment]
Agreed, I don't want to patch my Xcode install either.  For now this feature is disabled on OSX.
