### ISSUE TITLE
Rust Embedding/Binding

### ISSUE THREAD

**Issue by Immortalin** [Morgan-Stanley/hobbes#269]
How difficult would it be to bind/embed this in Rust?

**Comment by kthielen** [comment]
I haven't looked into it, so I can't give a good answer.  Probably some things would be easier to port than others.  Can we do static reflection on type structure in Rust?  That would allow us to avoid some of the macro meta-programming gymnastics that we have to do for binding (and structured storage in files/shm, serialization, compression, ...) in C++.

It's probably a worthwhile thing to do, since Rust covers use-cases similar to C++ and can similarly make use of type structure in the way that we do for our various uses for hobbes.

**Comment by Immortalin** [comment]
That's good to hear, we use a lot of Rust here at KloudTrader and Hobbes looks really interesting.

**Comment by kthielen** [comment]
Thanks.  Your product looks interesting as well.

Although I can't comment on trading methods, I can say that we do have some large-scale production uses for hobbes.  You might find the structured logging feature useful, and the format we have for data structure persistence in files/shm (where "native" data structures can be persisted and viewed equally from C++, hobbes, python -- maybe a good start with Rust would be to add it to that list).  I haven't written much about it, but we have a custom statistical compression method in here (hobbes/include/cfregion.H) that builds on top of that idea to efficiently write very large structured datasets, which also could be ported to Rust (it's basically arithmetic coding + probabilities-as-types, or an extension of Curry-Howard to probabilities).

**Comment by Immortalin** [comment]
@kthielen on an unrelated note, I have been trying to compile it to WebAssembly. Very difficult (the LLVM bit especially).

**Comment by Immortalin** [comment]
@kthielen might want to watch this: https://github.com/kloudtrader-github/Susie

**Comment by kthielen** [comment]
Thanks, sounds interesting but it looks like there’s no code there (yet?).

I made a workalike q interpreter once and Kx threatened to sue me personally, the company I worked for, and our clients.  You might want to be careful of those guys, they’re very spiteful and have an inflated sense of importance.
