### ISSUE TITLE
Accessing member variable is not consistent

### ISSUE THREAD

**Issue by brianegge** [Morgan-Stanley/hobbes#273]
Perhaps this is user error, but we're not able to get/set member variables as expected.

```
> hi
> x = {a=0, b=0}
> x.a <- 42

> x.a
0
> x
{a=42, b=0} 
```

It works fine with newPrim(), thought the values are then not default initialized to zero.
```
> x = newPrim()::{a:int, b:int}
> x.a <-42

> x
{a=42, b=65543}
> x.a
42 
```

**Comment by kthielen** [comment]
Yeah, this is down to an issue with the way that LLVM treats constants (usually good where we can optimize code knowing the value of these constants).  We could change the back-end to always allocate mutable memory locations for constants, though it would block constant optimization and might slightly penalize latency-critical code that uses constants (since it would have to go to memory where it might otherwise use immediate values).

**Comment by kthielen** [comment]
FWIW, there's also "newPrimZ" to allocate fixed-length mutable memory that's zero-initialized:

```
> m=newPrimZ()::{x:int,y:int}
> m.x<-42

> m
{x=42, y=0}
```

**Comment by kthielen** [comment]
(Most code shouldn't have stuff like this, things generally are nicer with hobbes as a "query language".)

**Comment by brianegge** [comment]
Why are we able to partially mutate the 'constant'? I can see the first syntax creating a constant and the second one create a mutable object on the stack, but it seems in the first case then you shouldn't be able to assign to it. NB., it is being used to setup a complicated match expression.

**Comment by kthielen** [comment]
The reason it's allowed is that mutability isn't tracked in the type system.  A long time ago, I'd considered using a monad to distinguish the two modes, but I had already heard so many complaints about the more limited type system (just structural algebraic types and constraints) being "difficult to understand" so I left it alone.  It would be worth considering.

You're using it to generate a match expression, like as text?  Or you're using a structure with guards and you want to change a field to change the behavior of the match?

I guess for now, newPrim or newPrimZ would be the way to go for that case.

**Comment by brianegge** [comment]
Suppose we want to classify people if they are a child, adult or retired based on age, but depending on where the person lives these ranges are different. So first we setup some age range objects and then use those ranges in a match. Using `newPrimZ` works fine and we just need to remember to use the shorter initialization only for immutable objects.

**Comment by baiyanhuang** [comment]
Thanks Kalani, that explains a lot, just one more question: why in first case, when we print the constant x, it actually shows the mutated value of x.a?

**Comment by kthielen** [comment]
LLVM works in mysterious ways, but my guess is that LLVM owns the block of constant memory and we're able to write into it just like with any other memory.  However, because it has decided that the memory is constant, then it's free to replace code referencing that data with immediate values wherever it wants.

Sometimes it does that replacement, sometimes it doesn't.

I'm working on a low-level replacement for LLVM, should be able to better point to file/line for questions like this in the future (but still will need to distinguish constant and mutable data as Brian suggested).
