### ISSUE TITLE
Pattern Extensions

### ISSUE THREAD

**Issue by skaller** [Morgan-Stanley/hobbes#33]
Just suggestions! It useful to have multiple possible patterns with one handler:

```
| X= (a,b) | Y= (b,a) -> ....
```

It is even more useful if you add a "with" clause:

```
| Complex =(x,y) | Real =(x) with y = 0.0 -> ...
```

In principle these can be nested as well, including any guards. BTW I have no idea how you do exhaustion analysis when guards are used.

I'm not sure about the syntax. I think your current syntax is wrong. This syntax:

```
match e1 e2 e3 with
| p1 p2 p3 where C -> ...
```

is silly. You should get rid of the multiple values, there's no point to it, it gets in
the way of generalisations like the ones I outlined above, and the effect can be
obtained using tuples anyhow:

```
match (e1,e2,e3) with
| (p1,p2, p3) where C -> ...
```

Given that, the where clauses can be nested and you can add the with clause.
Indeed, any number each in any order. You could then write

```
| (A | B with .. | D where ... )
```

kind of thing. I can do these in Felix. I actually cheat by flattening the matches
and then replicating the handlers which allows the variables to be generic
but you probably don't want to do that (I desugar pattern matches before
type analysis which is a bad idea but simplifies the compiler).

Felix also supports *user defined matches*. To do that you pick a pseudo
constructor name, then define two functions based on that name:
one to see if a value matches or not, and one to extract the constructor argument.
Felix actually defined "Snoc" instead of "Cons" for lists, because it puts the pointer
first, allowing some operations to be universal (independent of the value type).
I then have a "user defined constructor" named "Cons" you can match against
in the expected order. I think F# has something like this. If you do this kind of
thing you cannot check for exhaustion (so the user will have to add a wildcard
at the end).

Another really painful thing with pattern matching is that you cannot use defined
values in a pattern easily. You have to first bind a variable and then use a guard,
in Felix I allow something like:

```
let x = 1 in match y with 
| $(x) -> "one"
```
This allows one to use "manifest constants" in patterns. Means the same as

```
| z where z == x -> "one"
```

**Comment by kthielen** [comment]
Interesting ideas.  There is some code to support multiple pattern rows with a single handler as you describe, but it isn't currently enabled (I've put several parser-related things on the back-burner hoping to make time to build the language parser on the included LALR parser generator).

"Wrong" seems a little strong in context, maybe "arbitrarily limited" if you want to be able to have a guard at any pattern rather than just the final one (granted, sounds like a promising idea).

I don't agree that it's silly to match on multiple values.  Even if you match on a tuple as you suggest, the first step of match decomposition will translate that example to a 3-column table (projecting out the fields to match).  Why not represent the full table?  I think your "with" suggestion can still work with that syntax.

There's a form of user-defined matching in place here as well.  Array matches go through the Array type class, record lookup in patterns goes through HasField, variant deconstruction goes through HasCtor.  Users can define such ways of viewing their types and match on them as if they were just arrays/records/variants.

Interesting idea about manifest constants.  I have also thought about doing that for internal bindings (e.g. '| z z -> "both eq"').  It might be very useful.

Exhaustion analysis in the presence of guards is conservative, we always assume that guards can fail.

**Comment by kthielen** [comment]
FWIW, I split this up into different issues so they can be addressed individually:

* https://github.com/Morgan-Stanley/hobbes/issues/39
* https://github.com/Morgan-Stanley/hobbes/issues/40

**Comment by skaller** [comment]
Language design isn't arbitrary, there are principles. In this case you have broken one of them, hence "wrong" and "silly". You have unnecessarily complicated the language adding a feature that you already had. The syntax saves some punctuation, which is the only grounds you have for supporting it. 

On the other hand, it make extensions hard to support, because the syntax is fragile: whitespace as a separator relies on the terms being parsed having definite boundaries. It's hard to say this precisely. A good example of minimalist syntax is Go and it is extremely bad. Generally, syntax should use terms which by default have an introducer, explicit separators, and terminators. Then you relax these rules in special cases to reduce on punctuation. As an example, infix notation. As an example of syntax gone mad: Felix infix operators .. yes, there are something like 23 level of precedence even *I* cannot remember. Fact is, I cannot remember C precedence, nor Ocaml.

What I'm saying is that it is wise to make a fairly robust syntax so that you can easily support extensions and changes without disturbing much. Juxtaposition is often used for application. It is in Haskell and Felix and Ocaml but not C++. Which has the nice effect that parens () always mean grouping. C/C++ is a nightmare, because this isn't so.

So why introduce a fragile construction which as it turns out just duplicates existing functionality and gets in the way of extensions?

Consider 

```
pattern where expression pattern where expression
```

for example. How does the parser delimit the first guard expression from the second pattern?

**Comment by kthielen** [comment]
OK, there's a lot that we could say about syntax and parsing but I think that this is a different issue than how/what we accept in pattern match expressions.  I'm inclined to close this issue and expand it into multiple issues each with a more specific focus.  You've brought up a lot of good points but I want to reduce them to minimal discrete actionable tasks.
