### ISSUE TITLE
Hobbes not reentrant

### ISSUE THREAD

**Issue by skaller** [Morgan-Stanley/hobbes#36]
Quick look at the C++ embedding example seems to indicate the system isn't reentrant.
Not sure how easy that is to fix. The golden rule in C/C++ is never never never ever
use global variables.

This indicates the problem:

```
    hobbes::resetMemoryPool();
```

The standard way to do this is to have a function which creates a handle, which is then passed around. Just FYI here is the test case in the README, in Felix:

```
type hobbes_cc = "::hobbes::cc*" 
  requires package "hobbes"
;

ctor hobbes_cc : unit = "new ::hobbes::cc";

type hobbes_proc = "hobbes_proc" 
  requires header "typedef void (*hobbes_proc)(void);"
;

fun compileProc: hobbes_cc * string -> hobbes_proc = 
  "$1->compileFn<void()>($2)"
;

proc runProc: hobbes_proc = "$1();";

proc hobbes_resetMemoryPool : hobbes_cc = "hobbes::resetMemoryPool();" 
  requires package "hobbes"
;

var cc = hobbes_cc();

hobbesloop: while true do
  var s = readln stdin;
  if s == ":q\n" break hobbesloop;
  var x = "print(" + s + ")";
  var p = compileProc (cc, x);
  runProc p;
  println$ "Read s="+s;
  hobbes_resetMemoryPool cc;
done
```

No error handling yet. The compile should be polymorphic.
The package "hobbes" does all the header file inclusion and linkage required.
Here's the database entry I'm using:

```
Platform: OSX
Description: hobbes
provides_slib: -L/usr/local/lib -lhobbes
requires_slibs: -lz -lncurses -L/usr/local/lib  -lLLVMPasses -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMMCJIT -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMX86Disassembler -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMX86AsmParser -lLLVMX86Desc -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMObject -lLLVMBitReader -lLLVMCore -lLLVMMCDisassembler -lLLVMMCParser -lLLVMMC -lLLVMSupport -lLLVMDemangle
cflags: -I/usr/local/include
includes: '<hobbes/hobbes.H>'
```

**Comment by kthielen** [comment]
resetMemoryPool should be OK, it resets a thread-local region.  We do run compiled expressions concurrently very often in production, even ones that allocate.  The hobbes compiler itself definitely has to be protected with a lock (which so far has been acceptable for us), but the compiled output doesn't.

I have run into some problems in the past with calling into LLVM from multiple threads, even with one LLVM context per thread.

Also the flex/bison parser produces some code that has to be locked I think.  It might be possible to update it or invoke the parser generator in such a way that it doesn't have this problem.

For producing unique names, there's a global counter (various ways that this could be done differently).

And also there's a global type map held so that type desc pointers are uniquely determined by their constructor arguments (which makes structural type equality checking much faster!).

Those are the main issues I can think of that relate to this question.  I'm curious to know more about any problems you run into.

**Comment by kthielen** [comment]
Closing this issue as there doesn't seem to be a specific bug or change suggested.

**Comment by skaller** [comment]
There is a change suggested: remove all global variables. The quick and dirty method is to put all of them in a struct, allocate it in the mainline, and pass a pointer to it to every function that needs it, directly or indirectly. Possible exceptions to the rule: coverage, debugging, and other instrumentation. This also ensures you don't have any C++ order of initialisation problems, because there's nothing to initialise except independent constants.

There is a serious problem here: the resetMemory is *decoupled* from running the generated code which is *decoupled* from running the compiler. Here in Felix, from my actual working binding of hobbes with modifications:

```
  var x = read io.inp;
  var p = compileProc (cc, x);
  write (io.status, "compiled");
  runProc p;
  write (io.status, "run");
  hobbes_resetMemoryPool;
```

Do you see those read and write instructions? They cause an *exchange of control*. Felix uses coroutines. When this happens, the scheduler can run any active coroutine. What happens if I have another coroutine *also* using hobbes? The Felix code you see is translated to C++ by control inversion which ends up being mesh of callbacks, and whilst they have to be called in order, some other coroutine can be called in an interleaved manner. Cooperative multi-tasking.

C++17 has a weak form of coroutines now. So this isn't just a problem for Felix.

My point here is that reentrancy isn't just for pre-emptive threading. It's also necessary for recursion, and any other mechanism in which control is interleaved, including asynchronous I/O and event handling such as a generalisation of signals, etc.

**Comment by kthielen** [comment]
OK, you bring up a legitimate concern and we could reduce this issue to just "remove all global variables" and support the request with your example.  TBH, I think that "support reentrant region allocation" is more focused and actionable.  I don't think that a global type desc map is relevant to your example yet it's covered by "remove all global variables", but not justified by your program.

I totally agree with your line of reasoning but just want to focus the issue so that e.g. folks we have internally who might work on this project don't go on a snipe hunt.

**Comment by skaller** [comment]
By global variables I mean ones that *vary*. Global constants are OK. It is also ok to have certain kinds of protected variables that are constructed by mutation initially, these are really constants that take time to define.

With your reset of the region pool you have an additional problem: it is reset dynamically, so even if the reset dispatches off an explicit handle, you still have the problem of timing it correctly. You really need some form of linear typing here. Perhaps C++ itself can help, with unique_ptr<> or something?

IMHO whilst not optimal a manually specified protocol of operations which you have to follow is OK, the reentrancy issue comes down to the fact that the client *cannot* control it. 

C++ does this all over the place: invalid iterators etc. Its sometimes hard to do right,
but the protocol for correct usage is well specified in the Standard.

**Comment by kthielen** [comment]
Yes, linear typing for region-allocated data and maybe explicit region passing to compiled functions.  That's a very good idea.  I've also considered that before but haven't spent the time yet to make it happen.  I completely agree with your line of reasoning here.
