### ISSUE TITLE
Core Dump when binding a function which return the fileref value.

### ISSUE THREAD

**Issue by dawa79** [Morgan-Stanley/hobbes#368]
With the PullRequest #352 ,   it brings a new issue,  the test case is like:

   1) create 2 stream in slog file, call "test" and "testdup".  in testdup it just save the string ref of the same string in "test"
   2) bind 2 function for TestCase::save and TestCase::dup,  TestCase::save return the strref pointer
   3) Call a hobbes function "printRef“ to print the strref::index ,  this value seems the wrong value
   4) duplicate the string created by step 2),  it destroy the slog file.
   5) if we don't not call printRef, everything is OK.  in printRef, we only convert it to long type value. 

any idea on this issue？

here is the test case code:
------------------------------------------------------------------------------------------------------------------------------------

[test.txt](https://github.com/Morgan-Stanley/hobbes/files/4955451/test.txt)

**Comment by dawa79** [comment]
One more thing is 
   strref save(hobbes::array* a)
if the return strref type not pointer type, it will make coredump.

**Comment by kthielen** [comment]
It seems like you've done a lot of work to narrow down a problem, which I'd be happy to look into.  Your program here doesn't compile though, could you rework it so that it does compile and reproduce the problem you're seeing?  If you're hitting a problem getting your test program to compile, I can help with that too (just let me know what problems you hit and I will explain).

**Comment by dawa79** [comment]
namespace hobbes {
template <typename T, bool InStruct>
struct lift< fileref<T>*, InStruct > {
static MonoTypePtr type(typedb& tenv) {
return fileRefTy(lift<T, false>::type(tenv));
}
};
}

typedef hobbes::fileref<hobbes::array<char>*> strref;
struct TestCase{
TestCase(hobbes::cc*c, hobbes::writer* w): db(w), s(c, db, "test"), dup_s(c, db, "testdup"){}
strref* save(hobbes::array<char>* a) {
auto v = hobbes::makeStdString(a);
auto r = db->store(v);
s(r, false);
return hobbes::make(r);
}

void dup(strref& v){
   dup_s(v, false);
}
hobbes::writer* db;
hobbes::series<strref> s;
hobbes::series<stref> dup_s;
};

void runTest(){
hobbes::cc ctx;
auto* db = new hobbes::writer("/var/tmp/test.log");
auto* tc = new TestCase(&ctx, db);
ctx.bind("tc", tc);
ctx.bind("persist", memberfn(&TestCase::save));
ctx.bind("dup", memberfn(&TestCase::dup));

std::string module = R"(
save :: [char] -> [char]@?
save x = tc.persist(x)
s = save("test")
printRef :: long-> ()
printRef x = do { putStrLn(show(x)) ;}
printRef(convert(s))
tc.dup(s)
)";

hobbes::compile(&ctx, ctx.readModule(module));
}

int main(int,  char**){
runTest();
return 0;
}

**Comment by dawa79** [comment]
namespace hobbes {
template <typename T, bool InStruct>
struct lift< fileref<T>*, InStruct > {
static MonoTypePtr type(typedb& tenv) {
return fileRefTy(lift<T, false>::type(tenv));
}
};
}

typedef hobbes::fileref<hobbes::array<char>*> strref;
struct TestCase{
TestCase(hobbes::ccc, hobbes::writer* w): db(w), s(c, db, "test"), dup_s(c, db, "testdup"){}
strref* save(hobbes::array<char>* a) {
auto v = hobbes::makeStdString(a);
auto r = db->store(v);
s(r, false);
return hobbes::make<strref>(r);
}

void dup(strref& v){
dup_s(v, false);
}
hobbes::writer* db;
hobbes::series<strref> s;
hobbes::series<strref> dup_s;
};

void runTest(){
hobbes::cc ctx;
auto* db = new hobbes::writer("/var/tmp/test.log");
auto* tc = new TestCase(&ctx, db);
ctx.bind("tc", tc);
ctx.bind("persist", memberfn(&TestCase::save));
ctx.bind("dup", memberfn(&TestCase::dup));

std::string module = R"(
save :: [char] -> [char]@?
save x = tc.persist(x)
s = save("test")
printRef :: long-> ()
printRef x = do { putStrLn(show(x)) ;}
printRef(convert(s))
tc.dup(s)
)";

hobbes::compile(&ctx, ctx.readModule(module));
}

int main(int, char**){
runTest();
return 0;
}

**Comment by dawa79** [comment]
namespace hobbes {
template <typename T, bool InStruct>
struct lift< fileref<T>*, InStruct > {
static MonoTypePtr type(typedb& tenv) {
return fileRefTy(lift<T, false>::type(tenv));
}
};
}

typedef hobbes::fileref<hobbes::array<char>*> strref;
struct TestCase{
TestCase(hobbes::ccc, hobbes::writer w): db(w), s(c, db, "test"), dup_s(c, db, "testdup"){}
strref* save(hobbes::array<char>* a) {
auto v = hobbes::makeStdString(a);
auto r = db->store(v);
s(r, false);
return hobbes::make<strref>(r);
}

void dup(strref& v){
dup_s(v, false);
}
hobbes::writer* db;
hobbes::series<strref> s;
hobbes::series<strref> dup_s;
};

void runTest(){
hobbes::cc ctx;
auto* db = new hobbes::writer("/var/tmp/test.log");
auto* tc = new TestCase(&ctx, db);
ctx.bind("tc", tc);
ctx.bind("persist", memberfn(&TestCase::save));
ctx.bind("dup", memberfn(&TestCase::dup));

std::string module = R"(
save :: [char] -> [char]@?
save x = tc.persist(x)
s = save("test")
printRef :: long-> ()
printRef x = do { putStrLn(show(x)) ;}
printRef(convert(s))
tc.dup(s)
)";

hobbes::compile(&ctx, ctx.readModule(module));
}

int main(int, char**){
runTest();
return 0;
}

**Comment by dawa79** [comment]
I update the a file.  it should be ok.  you can check the slog file: /var/tmp/test.log.  the stream testdup has been destroyed

**Comment by kthielen** [comment]
Does that program compile for you?

**Comment by dawa79** [comment]
> Does that program compile for you?

Yes.

**Comment by kthielen** [comment]
Darn, I see what's going on.  I should have included a check for this when I introduced this fileref type.  I will post an update shortly.

**Comment by kthielen** [comment]
Sorry about this Dan, I hope it hasn't caused you too much stress.  It looks like this change affected how `fileref` values are passed in return values.  I fixed this, and verified the expected behavior with a test (first verifying that the test failed prior to my fix): https://github.com/Morgan-Stanley/hobbes/pull/369

**Comment by kthielen** [comment]
By the way, it might not be obvious from the content of the PR, but these `fileref` values are meant to be returned by value rather than by reference.  It's a slightly dangerous game doing this, because although gcc will always pass a naked int64 in a register, it might decide not to do that for structs wrapping an int64 (as in this case).

The only reason we do that wrap here is to signify the "intent" of the int64 (that it "means" an offset into a file where a `T` is stored).

So that part of the binding can be simplified at least, and the fundamental problem here was that gcc decided it'd be better to rewrite `fileref f(x)` into `void f(fileref*, x)` but our interpreter/compiler didn't know about that decision.  In this case a simple test can verify that at least, so I added it.

**Comment by dawa79** [comment]
Thanks for quick fix!
