### ISSUE TITLE
support match table "fall through"

### ISSUE THREAD

**Issue by kthielen** [Morgan-Stanley/hobbes#39]
In match tables where multiple contiguous rows have different pattern columns but identical result expressions, it would be helpful to support syntax such that the result expression only has to be written once.

e.g.:

```
match 1 2 3 with
| 1 x 3
| 1 2 x -> x
| _ _ _ -> 20
```

The first and second row share the same result expressions and so the first row can leave it unspecified expecting that it can be provided by a subsequent row.

As suggested by @skaller this can be supported for rows with differing sets of variables by requiring explicit bindings for unbound variables.

e.g.:

```
match 2 2 3 with
| 1 x y
| x 2 3 -> x+y
| _ _ _ -> 20
```

... will not compile, because the second row doesn't introduce a binding for "y" although its result expression requires it (but it would work for the first row which _does_ introduce a binding for "y").  To make this work, we can introduce a local binding as in Felix with:

```
match 2 2 3 with
| 1 x y
| x 2 3 with y = 40 -> x+y
| _ _ _ -> 20
```

... would compile and return 42 because the input just matches the second row, so x=2 and at this row we've explicitly bound y=40 so the final result is x+y=42.

**Comment by skaller** [comment]
I am think a bit more clearly now on the syntax issue. The current syntax is something like

```
"match" eatom+ "with"
"|" pattom+ "->" expr
...
```
where eatom is an atomic expression and pattom is an atomic pattern. Now when
you add the "with" clause you have a problem. You can do this:

```
"|" pattom+ ("with" ident "=" expr)* "->" expr
```

without a problem, but this syntax does not allow *nested* with clauses, it only works
on the end of a row of atomic patterns, and the expression is delimited by either
the next "with" or the "->". Ideally, the "with" should be allowed inside a pattern
as well. The same applies to guards, which have the syntax "where" expr.

Indeed, guards and with bindings have to be mixable in arbitrary order as well,
since the guard may require the with variable as part of its predicate, and the
with binding my be contingent on the guard passing. Think of division by zero here!

For example you want to write something like:

```
| ( Complex(x,y) | Real (x) with y==x) where y!=0 with r = x/y), Polar(r0,theta)) where r = r0 -> ...
```

which requires the where guard and with binder to be *nested* in the overall pattern,
so the conditions are established for the second match on the polar coordinates
to have a suitable guard. Felix can do this because the grammar makes the where
guards and with binding part of a pattern. So in Felix you cannot write this:

```
match .. with
| pat1
| pat2 -> ...
```

instead you have to write this:

```
match .. with
| (pat1 | pat2) -> ...
```

because syntactically, a match branch has the form of 

```
"|" pattern "->" expression
```
where the leading "|" is quite distinct from an internal "|" inside a pattern. 
The first code is missing the "->" and handler expression, its a syntax error.

When you allow nested guards, the order of evaluation matters.
You cannot just match the pattern and then apply the guards
with a logical conjunction. The issue here is that the "with" bindings can be
guarded as well. If you try to make the binding r=x/y and y is zero
you have an error: the guard must be applied first.

Maybe I can say this another way: you have an "open form" with a sequence of
match expressions and patterns, and you can have an "open form" applying
a guard to several pattern lines followed by the handler expression.
The problem is that the "open form" does not generalise: it isn't recursive,
it won't support nesting: nested patterns have to have a closed form.

"with" bindings should be nestable, but they have to be guardable 
inside the nesting as well (division by zero issue), which means you have
to allow nestable alternatives.

You can do this all with a closed form, and you can repeat the grammar
in an open form as well, but it is a lot of extra complexity.

The open form is not useless, it just isn't as general as it could be.
You need, basically:

```
pattern = pattern "with" binding
pattern = pattern "where" expression
pattern = pattern "|" pattern
pattern = "(" pattern ")"
```

with some precedence rules. You already have

```
pattern = "(" pattern "," pattern ... ")"
```

for tuples (and records and sums, pattern variables, wild cards,
constructors, integer literals, strings, etc).

The problem is you also have

```
pattern_row = "|" pattern pattern pattern ...
``

and

```
pattern_alternatives = pattern_row pattern_row ... "->" expression
```

and by the first syntax  a "where" guard binds to the last pattern not
the whole set of alternatives, and the "with" clause also binds to
the last pattern, not the whole row, *and you cannot fix it by
adding parentheses*.

Whereas if you throw out pattern_row and pattern_alternatives
the problem goes away, you can use parentheses to control
what the where and with clauses bind to.

I'm not sure what the solution is (without breaking your existing
syntax) other than to provide *both* forms. If that's even possible.

**Comment by kthielen** [comment]
Thanks @skaller, very good points.  We have room to break existing syntax if we need to, and you've made a very good case for with/where attached to patterns rather than rows (as currently implemented).

**Comment by skaller** [comment]
But don't change anything immediately! You can, for example, think about whether you can keep multi-row patterns as well. You could implement something with a new keyword to experiment, such as "generalisedmatch". That leaves all existing code intact. You can also look to see whether the parser can distinguish single argument and multi-argument matches, and treat them differently. Maybe not a good idea. This one is an extension, so you can put it on the back burner, the main risk is that too may people will use a syntax which you may want to break, better to do that early than late.

I'd put the reentrancy issue higher because it is a fundamental core design thing.
Look at Python, or other embeddable systems: the general rule is to always
construct a handle to the processor so you have a way to encapsulate state.
Systems that failed to do this cause problems down the track.
An example is OpenGL. Implicit context. Very bad.
