### ISSUE TITLE
match references to ambient variables

### ISSUE THREAD

**Issue by kthielen** [Morgan-Stanley/hobbes#40]
Sometimes we want to refer to the contents of a dynamic variable during a match (whether locally or externally defined).  It would be useful if there was support for this without having to resort to guards.

e.g.

```
eqTest x y d = match x y with
| z z -> "both are equal"
| _ d -> "at least y is equal to the given d"
| _ _ -> "who knows?"
```

**Comment by skaller** [comment]
This example involves a non-linear match which can be desugared by using a fresh variable and a guard with equality predicate. Similarly it would be useful to allow a named constant in a match:

```
one = 1
match x with | one -> ...
```

fails because "one" not a pattern, in particular, it isn't a constructor. Felix allows

```
match x with | $(expr) ->
```

which desugars to a pattern variable with an equality predicate. I think this is slightly different to a non-linear match (where the pattern variable is repeated).
